### ISSUE TITLE
Institution address

### ISSUE THREAD

**Issue by netbofia** [forestbiotech-lab/BrAPI#48]
Institution address is not explicitly placed in the database.

But can be differed to **Location** -> **LocationAdditionalInfo**: "propertyName":Address

Suggestion: Column address varchar(254) DEFAULT NULL in table **Institution**

##### Reference:
https://github.com/plantbreeding/API/tree/master/Specification/Studies#get-studies-by-studydbid--get-brapiv1studiesstudydbid

**Comment by DanFaria** [comment]
Even though, from a querying perspective, it would be easier to have the instituteAddress directly in the Institution table, it's not a good SQL practice to have locations/addresses stored in two distinct places (since locations include institutional addresses). What I think we are missing and should add is a column "streetAddress" in table Location. This way, with the locationId in table Institution, you can get all the information you need from table Location, and we have all locations stored in one place.

**Solution:** Add column streetAddress to table Location; define a unique key/index out of (name, street address, latitude, longitude) for that table, to ensure good behavior.

**Comment by netbofia** [comment]
https://docs.google.com/document/d/11_gsrqcYAD90mNKOLkFpiEfAuhe-6SfImPuvRBZYXr0/edit?usp=sharing

Differed unique key for later to allow flexibility.
